image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd front-end
    - npm install ci
    - npm run build

python_tests:
  image: python:3
  stage: test
  script:
    - cd back-end
    - pip3 install -r requirements.txt
    - python tests.py
  
postman_tests:
  stage: test
  image:
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - cd back-end
    - newman --version
    - newman run postman_tests.json

