image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd front-end
    - npm install ci
    - npm run build

python_tests:
  image: python:3
  stage: test
  script:
    - cd back-end
    - pip3 install -r requirements.txt
    - python tests.py
  
postman_tests:
  stage: test
  image:
    name: postman/newman:alpine
    entrypoint: [""]
  script:
    - cd back-end
    - newman --version
    - newman run postman_collection.json

frontend_tests:
  stage: test
  script:
    - cd front-end
    - npm install react-scripts
    - npm test
  
selenium:
  stage: test
  image: python:latest
  script:
    - cd front-end
    - cd selenium-tests
    - pip3 install selenium
    - apt-get update -y \ && apt-get install --no-install-recommends --no-install-suggests -y tzdata ca-certificates bzip2 curl wget libc-dev libxt6 \ && apt-get install --no-install-recommends --no-install-suggests -y `apt-cache depends firefox-esr | awk '/Depends:/{print$2}'` \ && update-ca-certificates \ && apt-get purge -y --auto-remove \ -o APT::AutoRemove::RecommendsImportant=false \ && rm -rf /var/lib/apt/lists/* /tmp/*
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz && \ tar -zxf geckodriver-v0.31.0-linux64.tar.gz -C /usr/local/bin && \ chmod +x /usr/local/bin/geckodriver && \ rm geckodriver-v0.31.0-linux64.tar.gz
    - FIREFOX_SETUP=firefox-setup.tar.bz2 && \ wget -O $FIREFOX_SETUP "https://download.mozilla.org/?product=firefox-95.0.1&os=linux64" && \ tar xjf $FIREFOX_SETUP -C /opt/ && \ ln -s /opt/firefox/firefox /usr/bin/firefox && \ rm $FIREFOX_SETUP
    - python3 -m navbarTests
