version: '3'
services:
  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./front-end:/app"
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./back-end:/app"
