version: '3'
services:
  backend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
